In [245]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.preprocessing import StandardScaler

In [246]:
df = pd.read_csv("datasets/housedata_cleaned.csv")
df2 = pd.read_csv("datasets/Final_housingdata.csv")

In [247]:
df.dtypes

Unnamed: 0            int64
PID                   int64
Property Address     object
Property City        object
House Type           object
Sale Price(USD)       int64
Sale Date            object
Latitude            float64
Longitude           float64
Zone                  int64
dtype: object

In [248]:
df2['Bar'] = df2['Unnamed: 18']

In [249]:
df2

,PID,Property Address,Property City,House Type,Sale Price(USD),Sale Date,Latitude,Longitude,Zone,Restaurants,Supermarkets,Liquor Store,Schools,Churches,Convenience_Store,Drugstore,Fire_Station,Hospital,Unnamed: 18,Bar
0,1,1100 CHEYENNE CIR,MADISON,SINGLE FAMILY,304000,9/7/2021,36.252414,-86.670697,6,20,7,8,20,20,20,8,2,2,20,20
1,2,3450 GREER RD,GOODLETTSVILLE,SINGLE FAMILY,405000,9/17/2021,36.383536,-86.783246,5,16,0,2,9,11,5,2,0,0,0,0
2,3,8565 WHITES CREEK PIKE,JOELTON,SINGLE FAMILY,666500,9/22/2021,36.381169,-86.894571,5,1,0,1,1,10,2,0,0,0,0,0
3,4,8560 COOPERTOWN RD,JOELTON,SINGLE FAMILY,620000,9/20/2021,36.380810,-86.906122,5,3,0,2,1,10,5,0,0,0,0,0
4,5,8409 RILEY ADCOCK RD,JOELTON,SINGLE FAMILY,227500,9/17/2021,36.372914,-86.883644,5,1,0,0,1,5,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,1214,4232 DYSANT ALY,NOLENSVILLE,SINGLE FAMILY,460000,9/13/2021,35.985114,-86.662269,1,20,2,5,20,20,7,4,1,6,2,2
1214,1215,1983 CAROTHERS RD,NOLENSVILLE,SINGLE FAMILY,497300,9/27/2021,35.984074,-86.622866,1,20,1,3,10,20,13,2,2,2,3,3
1215,1216,307 MOIRA CIR,NOLENSVILLE,RESIDENTIAL CONDO,300400,9/28/2021,35.983315,-86.622208,1,20,1,3,10,20,13,2,2,2,4,4
1216,1217,4154 ALVA LN,NOLENSVILLE,SINGLE FAMILY,500000,9/3/2021,35.983120,-86.663883,1,20,2,5,20,20,7,4,1,6,2,2
1217,1218,2027 OAK TRAIL DR,NOLENSVILLE,RESIDENTIAL CONDO,378900,9/13/2021,35.982863,-86.617761,1,20,1,4,8,18,15,2,3,6,5,5

In [250]:
df2 = df2.drop(columns='Unnamed: 18')
df2

,PID,Property Address,Property City,House Type,Sale Price(USD),Sale Date,Latitude,Longitude,Zone,Restaurants,Supermarkets,Liquor Store,Schools,Churches,Convenience_Store,Drugstore,Fire_Station,Hospital,Bar
0,1,1100 CHEYENNE CIR,MADISON,SINGLE FAMILY,304000,9/7/2021,36.252414,-86.670697,6,20,7,8,20,20,20,8,2,2,20
1,2,3450 GREER RD,GOODLETTSVILLE,SINGLE FAMILY,405000,9/17/2021,36.383536,-86.783246,5,16,0,2,9,11,5,2,0,0,0
2,3,8565 WHITES CREEK PIKE,JOELTON,SINGLE FAMILY,666500,9/22/2021,36.381169,-86.894571,5,1,0,1,1,10,2,0,0,0,0
3,4,8560 COOPERTOWN RD,JOELTON,SINGLE FAMILY,620000,9/20/2021,36.380810,-86.906122,5,3,0,2,1,10,5,0,0,0,0
4,5,8409 RILEY ADCOCK RD,JOELTON,SINGLE FAMILY,227500,9/17/2021,36.372914,-86.883644,5,1,0,0,1,5,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,1214,4232 DYSANT ALY,NOLENSVILLE,SINGLE FAMILY,460000,9/13/2021,35.985114,-86.662269,1,20,2,5,20,20,7,4,1,6,2
1214,1215,1983 CAROTHERS RD,NOLENSVILLE,SINGLE FAMILY,497300,9/27/2021,35.984074,-86.622866,1,20,1,3,10,20,13,2,2,2,3
1215,1216,307 MOIRA CIR,NOLENSVILLE,RESIDENTIAL CONDO,300400,9/28/2021,35.983315,-86.622208,1,20,1,3,10,20,13,2,2,2,4
1216,1217,4154 ALVA LN,NOLENSVILLE,SINGLE FAMILY,500000,9/3/2021,35.983120,-86.663883,1,20,2,5,20,20,7,4,1,6,2
1217,1218,2027 OAK TRAIL DR,NOLENSVILLE,RESIDENTIAL CONDO,378900,9/13/2021,35.982863,-86.617761,1,20,1,4,8,18,15,2,3,6,5

In [251]:
joindf = df.merge(df2, on='Property Address')

In [252]:
joindf

,Unnamed: 0,PID_x,Property Address,Property City_x,House Type_x,Sale Price(USD)_x,Sale Date_x,Latitude_x,Longitude_x,Zone_x,...,Restaurants,Supermarkets,Liquor Store,Schools,Churches,Convenience_Store,Drugstore,Fire_Station,Hospital,Bar
0,0,1,1100 CHEYENNE CIR,MADISON,SINGLE FAMILY,304000,9/7/2021,36.252414,-86.670697,6,...,20,7,8,20,20,20,8,2,2,20
1,1,2,3450 GREER RD,GOODLETTSVILLE,SINGLE FAMILY,405000,9/17/2021,36.383536,-86.783246,5,...,16,0,2,9,11,5,2,0,0,0
2,2,3,8565 WHITES CREEK PIKE,JOELTON,SINGLE FAMILY,666500,9/22/2021,36.381169,-86.894571,5,...,1,0,1,1,10,2,0,0,0,0
3,3,4,8560 COOPERTOWN RD,JOELTON,SINGLE FAMILY,620000,9/20/2021,36.380810,-86.906122,5,...,3,0,2,1,10,5,0,0,0,0
4,4,5,8409 RILEY ADCOCK RD,JOELTON,SINGLE FAMILY,227500,9/17/2021,36.372914,-86.883644,5,...,1,0,0,1,5,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1230,1458,1459,4232 DYSANT ALY,NOLENSVILLE,SINGLE FAMILY,460000,9/13/2021,35.985114,-86.662269,1,...,20,2,5,20,20,7,4,1,6,2
1231,1459,1460,1983 CAROTHERS RD,NOLENSVILLE,SINGLE FAMILY,497300,9/27/2021,35.984074,-86.622866,1,...,20,1,3,10,20,13,2,2,2,3
1232,1460,1461,307 MOIRA CIR,NOLENSVILLE,RESIDENTIAL CONDO,300400,9/28/2021,35.983315,-86.622208,1,...,20,1,3,10,20,13,2,2,2,4
1233,1461,1462,4154 ALVA LN,NOLENSVILLE,SINGLE FAMILY,500000,9/3/2021,35.983120,-86.663883,1,...,20,2,5,20,20,7,4,1,6,2
1234,1462,1463,2027 OAK TRAIL DR,NOLENSVILLE,RESIDENTIAL CONDO,378900,9/13/2021,35.982863,-86.617761,1,...,20,1,4,8,18,15,2,3,6,5

In [253]:
joindf = joindf.set_index('PID_y')

In [254]:
joindf

,Unnamed: 0,PID_x,Property Address,Property City_x,House Type_x,Sale Price(USD)_x,Sale Date_x,Latitude_x,Longitude_x,Zone_x,...,Restaurants,Supermarkets,Liquor Store,Schools,Churches,Convenience_Store,Drugstore,Fire_Station,Hospital,Bar
PID_y,,,,,,,,,,,,,,,,,,,,,
1,0,1,1100 CHEYENNE CIR,MADISON,SINGLE FAMILY,304000,9/7/2021,36.252414,-86.670697,6,...,20,7,8,20,20,20,8,2,2,20
2,1,2,3450 GREER RD,GOODLETTSVILLE,SINGLE FAMILY,405000,9/17/2021,36.383536,-86.783246,5,...,16,0,2,9,11,5,2,0,0,0
3,2,3,8565 WHITES CREEK PIKE,JOELTON,SINGLE FAMILY,666500,9/22/2021,36.381169,-86.894571,5,...,1,0,1,1,10,2,0,0,0,0
4,3,4,8560 COOPERTOWN RD,JOELTON,SINGLE FAMILY,620000,9/20/2021,36.380810,-86.906122,5,...,3,0,2,1,10,5,0,0,0,0
5,4,5,8409 RILEY ADCOCK RD,JOELTON,SINGLE FAMILY,227500,9/17/2021,36.372914,-86.883644,5,...,1,0,0,1,5,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1214,1458,1459,4232 DYSANT ALY,NOLENSVILLE,SINGLE FAMILY,460000,9/13/2021,35.985114,-86.662269,1,...,20,2,5,20,20,7,4,1,6,2
1215,1459,1460,1983 CAROTHERS RD,NOLENSVILLE,SINGLE FAMILY,497300,9/27/2021,35.984074,-86.622866,1,...,20,1,3,10,20,13,2,2,2,3
1216,1460,1461,307 MOIRA CIR,NOLENSVILLE,RESIDENTIAL CONDO,300400,9/28/2021,35.983315,-86.622208,1,...,20,1,3,10,20,13,2,2,2,4
1217,1461,1462,4154 ALVA LN,NOLENSVILLE,SINGLE FAMILY,500000,9/3/2021,35.983120,-86.663883,1,...,20,2,5,20,20,7,4,1,6,2
1218,1462,1463,2027 OAK TRAIL DR,NOLENSVILLE,RESIDENTIAL CONDO,378900,9/13/2021,35.982863,-86.617761,1,...,20,1,4,8,18,15,2,3,6,5

In [255]:
joindf = joindf.drop(columns=['Sale Price(USD)_x','Sale Date_x','Property City_y','Sale Date_y','Latitude_y','Longitude_y'])
joindf

,Unnamed: 0,PID_x,Property Address,Property City_x,House Type_x,Latitude_x,Longitude_x,Zone_x,House Type_y,Sale Price(USD)_y,...,Restaurants,Supermarkets,Liquor Store,Schools,Churches,Convenience_Store,Drugstore,Fire_Station,Hospital,Bar
PID_y,,,,,,,,,,,,,,,,,,,,,
1,0,1,1100 CHEYENNE CIR,MADISON,SINGLE FAMILY,36.252414,-86.670697,6,SINGLE FAMILY,304000,...,20,7,8,20,20,20,8,2,2,20
2,1,2,3450 GREER RD,GOODLETTSVILLE,SINGLE FAMILY,36.383536,-86.783246,5,SINGLE FAMILY,405000,...,16,0,2,9,11,5,2,0,0,0
3,2,3,8565 WHITES CREEK PIKE,JOELTON,SINGLE FAMILY,36.381169,-86.894571,5,SINGLE FAMILY,666500,...,1,0,1,1,10,2,0,0,0,0
4,3,4,8560 COOPERTOWN RD,JOELTON,SINGLE FAMILY,36.380810,-86.906122,5,SINGLE FAMILY,620000,...,3,0,2,1,10,5,0,0,0,0
5,4,5,8409 RILEY ADCOCK RD,JOELTON,SINGLE FAMILY,36.372914,-86.883644,5,SINGLE FAMILY,227500,...,1,0,0,1,5,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1214,1458,1459,4232 DYSANT ALY,NOLENSVILLE,SINGLE FAMILY,35.985114,-86.662269,1,SINGLE FAMILY,460000,...,20,2,5,20,20,7,4,1,6,2
1215,1459,1460,1983 CAROTHERS RD,NOLENSVILLE,SINGLE FAMILY,35.984074,-86.622866,1,SINGLE FAMILY,497300,...,20,1,3,10,20,13,2,2,2,3
1216,1460,1461,307 MOIRA CIR,NOLENSVILLE,RESIDENTIAL CONDO,35.983315,-86.622208,1,RESIDENTIAL CONDO,300400,...,20,1,3,10,20,13,2,2,2,4
1217,1461,1462,4154 ALVA LN,NOLENSVILLE,SINGLE FAMILY,35.983120,-86.663883,1,SINGLE FAMILY,500000,...,20,2,5,20,20,7,4,1,6,2
1218,1462,1463,2027 OAK TRAIL DR,NOLENSVILLE,RESIDENTIAL CONDO,35.982863,-86.617761,1,RESIDENTIAL CONDO,378900,...,20,1,4,8,18,15,2,3,6,5

In [256]:
joindf = joindf.drop(columns=['House Type_y','Zone_y','Unnamed: 0','PID_x'])
joindf

,Property Address,Property City_x,House Type_x,Latitude_x,Longitude_x,Zone_x,Sale Price(USD)_y,Restaurants,Supermarkets,Liquor Store,Schools,Churches,Convenience_Store,Drugstore,Fire_Station,Hospital,Bar
PID_y,,,,,,,,,,,,,,,,,
1,1100 CHEYENNE CIR,MADISON,SINGLE FAMILY,36.252414,-86.670697,6,304000,20,7,8,20,20,20,8,2,2,20
2,3450 GREER RD,GOODLETTSVILLE,SINGLE FAMILY,36.383536,-86.783246,5,405000,16,0,2,9,11,5,2,0,0,0
3,8565 WHITES CREEK PIKE,JOELTON,SINGLE FAMILY,36.381169,-86.894571,5,666500,1,0,1,1,10,2,0,0,0,0
4,8560 COOPERTOWN RD,JOELTON,SINGLE FAMILY,36.380810,-86.906122,5,620000,3,0,2,1,10,5,0,0,0,0
5,8409 RILEY ADCOCK RD,JOELTON,SINGLE FAMILY,36.372914,-86.883644,5,227500,1,0,0,1,5,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1214,4232 DYSANT ALY,NOLENSVILLE,SINGLE FAMILY,35.985114,-86.662269,1,460000,20,2,5,20,20,7,4,1,6,2
1215,1983 CAROTHERS RD,NOLENSVILLE,SINGLE FAMILY,35.984074,-86.622866,1,497300,20,1,3,10,20,13,2,2,2,3
1216,307 MOIRA CIR,NOLENSVILLE,RESIDENTIAL CONDO,35.983315,-86.622208,1,300400,20,1,3,10,20,13,2,2,2,4
1217,4154 ALVA LN,NOLENSVILLE,SINGLE FAMILY,35.983120,-86.663883,1,500000,20,2,5,20,20,7,4,1,6,2
1218,2027 OAK TRAIL DR,NOLENSVILLE,RESIDENTIAL CONDO,35.982863,-86.617761,1,378900,20,1,4,8,18,15,2,3,6,5

In [257]:
joindf.columns

Index(['Property Address', 'Property City_x', 'House Type_x', 'Latitude_x',
       'Longitude_x', 'Zone_x', 'Sale Price(USD)_y', 'Restaurants',
       'Supermarkets', 'Liquor Store', 'Schools', 'Churches',
       'Convenience_Store', 'Drugstore', 'Fire_Station', 'Hospital', 'Bar'],
      dtype='object')

In [258]:
joindf = pd.get_dummies(joindf,columns=['House Type_x','Zone_x','Property City_x'])

In [259]:
joindf

,Property Address,Latitude_x,Longitude_x,Sale Price(USD)_y,Restaurants,Supermarkets,Liquor Store,Schools,Churches,Convenience_Store,...,Property City_x_BRENTWOOD,Property City_x_GOODLETTSVILLE,Property City_x_HERMITAGE,Property City_x_JOELTON,Property City_x_MADISON,Property City_x_NASHVILLE,Property City_x_NOLENSVILLE,Property City_x_OLD HICKORY,Property City_x_PEGRAM,Property City_x_WHITES CREEK
PID_y,,,,,,,,,,,,,,,,,,,,,
1,1100 CHEYENNE CIR,36.252414,-86.670697,304000,20,7,8,20,20,20,...,0,0,0,0,1,0,0,0,0,0
2,3450 GREER RD,36.383536,-86.783246,405000,16,0,2,9,11,5,...,0,1,0,0,0,0,0,0,0,0
3,8565 WHITES CREEK PIKE,36.381169,-86.894571,666500,1,0,1,1,10,2,...,0,0,0,1,0,0,0,0,0,0
4,8560 COOPERTOWN RD,36.380810,-86.906122,620000,3,0,2,1,10,5,...,0,0,0,1,0,0,0,0,0,0
5,8409 RILEY ADCOCK RD,36.372914,-86.883644,227500,1,0,0,1,5,1,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1214,4232 DYSANT ALY,35.985114,-86.662269,460000,20,2,5,20,20,7,...,0,0,0,0,0,0,1,0,0,0
1215,1983 CAROTHERS RD,35.984074,-86.622866,497300,20,1,3,10,20,13,...,0,0,0,0,0,0,1,0,0,0
1216,307 MOIRA CIR,35.983315,-86.622208,300400,20,1,3,10,20,13,...,0,0,0,0,0,0,1,0,0,0
1217,4154 ALVA LN,35.983120,-86.663883,500000,20,2,5,20,20,7,...,0,0,0,0,0,0,1,0,0,0
1218,2027 OAK TRAIL DR,35.982863,-86.617761,378900,20,1,4,8,18,15,...,0,0,0,0,0,0,1,0,0,0

In [260]:
joindf = joindf.dropna()

In [261]:
joindf.isna().sum()

Property Address                                    0
Latitude_x                                          0
Longitude_x                                         0
Sale Price(USD)_y                                   0
Restaurants                                         0
Supermarkets                                        0
Liquor Store                                        0
Schools                                             0
Churches                                            0
Convenience_Store                                   0
Drugstore                                           0
Fire_Station                                        0
Hospital                                            0
Bar                                                 0
House Type_x_CONDOMINIUM OFC  OR OTHER COM CONDO    0
House Type_x_DUPLEX                                 0
House Type_x_MOBILE HOME                            0
House Type_x_QUADPLEX                               0
House Type_x_RESIDENTIAL COMBO/MISC                 0
House Type_x_RESIDENTIAL CONDO                      0
House Type_x_RURAL COMBO                            0
House Type_x_SINGLE FAMILY                          0
House Type_x_SMALL SERVICE SHOP                     0
House Type_x_SPLIT CLASS                            0
House Type_x_TRIPLEX                                0
House Type_x_VACANT RESIDENTIAL LAND                0
House Type_x_VACANT RURAL LAND                      0
House Type_x_ZERO LOT LINE                          0
Zone_x_1                                            0
Zone_x_2                                            0
Zone_x_3                                            0
Zone_x_4                                            0
Zone_x_5                                            0
Zone_x_6                                            0
Zone_x_7                                            0
Zone_x_8                                            0
Zone_x_9                                            0
Property City_x_ANTIOCH                             0
Property City_x_BRENTWOOD                           0
Property City_x_GOODLETTSVILLE                      0
Property City_x_HERMITAGE                           0
Property City_x_JOELTON                             0
Property City_x_MADISON                             0
Property City_x_NASHVILLE                           0
Property City_x_NOLENSVILLE                         0
Property City_x_OLD HICKORY                         0
Property City_x_PEGRAM                              0
Property City_x_WHITES CREEK                        0
dtype: int64

In [262]:
joindf

,Property Address,Latitude_x,Longitude_x,Sale Price(USD)_y,Restaurants,Supermarkets,Liquor Store,Schools,Churches,Convenience_Store,...,Property City_x_BRENTWOOD,Property City_x_GOODLETTSVILLE,Property City_x_HERMITAGE,Property City_x_JOELTON,Property City_x_MADISON,Property City_x_NASHVILLE,Property City_x_NOLENSVILLE,Property City_x_OLD HICKORY,Property City_x_PEGRAM,Property City_x_WHITES CREEK
PID_y,,,,,,,,,,,,,,,,,,,,,
1,1100 CHEYENNE CIR,36.252414,-86.670697,304000,20,7,8,20,20,20,...,0,0,0,0,1,0,0,0,0,0
2,3450 GREER RD,36.383536,-86.783246,405000,16,0,2,9,11,5,...,0,1,0,0,0,0,0,0,0,0
3,8565 WHITES CREEK PIKE,36.381169,-86.894571,666500,1,0,1,1,10,2,...,0,0,0,1,0,0,0,0,0,0
4,8560 COOPERTOWN RD,36.380810,-86.906122,620000,3,0,2,1,10,5,...,0,0,0,1,0,0,0,0,0,0
5,8409 RILEY ADCOCK RD,36.372914,-86.883644,227500,1,0,0,1,5,1,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1214,4232 DYSANT ALY,35.985114,-86.662269,460000,20,2,5,20,20,7,...,0,0,0,0,0,0,1,0,0,0
1215,1983 CAROTHERS RD,35.984074,-86.622866,497300,20,1,3,10,20,13,...,0,0,0,0,0,0,1,0,0,0
1216,307 MOIRA CIR,35.983315,-86.622208,300400,20,1,3,10,20,13,...,0,0,0,0,0,0,1,0,0,0
1217,4154 ALVA LN,35.983120,-86.663883,500000,20,2,5,20,20,7,...,0,0,0,0,0,0,1,0,0,0
1218,2027 OAK TRAIL DR,35.982863,-86.617761,378900,20,1,4,8,18,15,...,0,0,0,0,0,0,1,0,0,0

In [263]:
import re

In [264]:
joindf['Add. #'] = joindf["Property Address"].str.extract('(\d{0,5})',expand=True)
joindf['Add. Name'] = joindf["Property Address"].str.extract('(\D{0,20}[A-Z][\s])',expand=True)
joindf['Add. End'] = joindf["Property Address"].str.extract('(\w{0,}\Z)',expand=True)

In [265]:
joindf

,Property Address,Latitude_x,Longitude_x,Sale Price(USD)_y,Restaurants,Supermarkets,Liquor Store,Schools,Churches,Convenience_Store,...,Property City_x_JOELTON,Property City_x_MADISON,Property City_x_NASHVILLE,Property City_x_NOLENSVILLE,Property City_x_OLD HICKORY,Property City_x_PEGRAM,Property City_x_WHITES CREEK,Add. #,Add. Name,Add. End
PID_y,,,,,,,,,,,,,,,,,,,,,
1,1100 CHEYENNE CIR,36.252414,-86.670697,304000,20,7,8,20,20,20,...,0,1,0,0,0,0,0,1100,CHEYENNE,CIR
2,3450 GREER RD,36.383536,-86.783246,405000,16,0,2,9,11,5,...,0,0,0,0,0,0,0,3450,GREER,RD
3,8565 WHITES CREEK PIKE,36.381169,-86.894571,666500,1,0,1,1,10,2,...,1,0,0,0,0,0,0,8565,WHITES CREEK,PIKE
4,8560 COOPERTOWN RD,36.380810,-86.906122,620000,3,0,2,1,10,5,...,1,0,0,0,0,0,0,8560,COOPERTOWN,RD
5,8409 RILEY ADCOCK RD,36.372914,-86.883644,227500,1,0,0,1,5,1,...,1,0,0,0,0,0,0,8409,RILEY ADCOCK,RD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1214,4232 DYSANT ALY,35.985114,-86.662269,460000,20,2,5,20,20,7,...,0,0,0,1,0,0,0,4232,DYSANT,ALY
1215,1983 CAROTHERS RD,35.984074,-86.622866,497300,20,1,3,10,20,13,...,0,0,0,1,0,0,0,1983,CAROTHERS,RD
1216,307 MOIRA CIR,35.983315,-86.622208,300400,20,1,3,10,20,13,...,0,0,0,1,0,0,0,307,MOIRA,CIR
1217,4154 ALVA LN,35.983120,-86.663883,500000,20,2,5,20,20,7,...,0,0,0,1,0,0,0,4154,ALVA,LN
1218,2027 OAK TRAIL DR,35.982863,-86.617761,378900,20,1,4,8,18,15,...,0,0,0,1,0,0,0,2027,OAK TRAIL,DR

In [266]:
joindf = pd.get_dummies(joindf,columns=['Add. End'])

In [267]:
joindf

,Property Address,Latitude_x,Longitude_x,Sale Price(USD)_y,Restaurants,Supermarkets,Liquor Store,Schools,Churches,Convenience_Store,...,Add. End_S,Add. End_ST,Add. End_STA,Add. End_TER,Add. End_TRCE,Add. End_TRL,Add. End_VILLA,Add. End_W,Add. End_WAY,Add. End_XING
PID_y,,,,,,,,,,,,,,,,,,,,,
1,1100 CHEYENNE CIR,36.252414,-86.670697,304000,20,7,8,20,20,20,...,0,0,0,0,0,0,0,0,0,0
2,3450 GREER RD,36.383536,-86.783246,405000,16,0,2,9,11,5,...,0,0,0,0,0,0,0,0,0,0
3,8565 WHITES CREEK PIKE,36.381169,-86.894571,666500,1,0,1,1,10,2,...,0,0,0,0,0,0,0,0,0,0
4,8560 COOPERTOWN RD,36.380810,-86.906122,620000,3,0,2,1,10,5,...,0,0,0,0,0,0,0,0,0,0
5,8409 RILEY ADCOCK RD,36.372914,-86.883644,227500,1,0,0,1,5,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1214,4232 DYSANT ALY,35.985114,-86.662269,460000,20,2,5,20,20,7,...,0,0,0,0,0,0,0,0,0,0
1215,1983 CAROTHERS RD,35.984074,-86.622866,497300,20,1,3,10,20,13,...,0,0,0,0,0,0,0,0,0,0
1216,307 MOIRA CIR,35.983315,-86.622208,300400,20,1,3,10,20,13,...,0,0,0,0,0,0,0,0,0,0
1217,4154 ALVA LN,35.983120,-86.663883,500000,20,2,5,20,20,7,...,0,0,0,0,0,0,0,0,0,0
1218,2027 OAK TRAIL DR,35.982863,-86.617761,378900,20,1,4,8,18,15,...,0,0,0,0,0,0,0,0,0,0

In [269]:
# Import dependencies
from sklearn.linear_model import LinearRegression

# Generate some data
X = joindf.drop(columns = ['Sale Price(USD)_y', 'Property Address','Latitude_x','Longitude_x','Add. #','Add. Name'])
y = joindf['Sale Price(USD)_y']

# Create a linear model
model = LinearRegression()

# Fit (train) our model to the data
model.fit(X, y)

LinearRegression()

In [270]:
from sklearn.metrics import mean_squared_error, r2_score

# Use our model to predict a value
predicted = model.predict(X)

# Score the prediction with MSE and R2
mse = mean_squared_error(y, predicted)
r2 = r2_score(y, predicted)

print(f"mean squared error (MSE): {mse}")
print(f"R-squared (R2 ): {r2}")

mean squared error (MSE): 20752354003.942966
R-squared (R2 ): 0.3694719298493906

In [271]:
# Overall Score for the model
model.score(X, y)

0.3694719298493906

In [272]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [273]:
model.fit(X_train, y_train)

LinearRegression()

In [277]:
model.score(X_train, y_train)

0.39322409310911854

In [274]:
model.score(X_test, y_test)

0.23044954168743081

In [275]:
coef = model.coef_
coef = list(coef)
coef

[5385.870077611788,
 -5307.364640970038,
 8616.47564063014,
 -11383.535888987888,
 7931.920374339745,
 -6445.332309981422,
 7.586703439172197,
 6527.27344943005,
 1924.141887626436,
 -2967.0187506123602,
 59195.52166435767,
 75684.37827907104,
 -147949.8319935349,
 -8772.93875523908,
 1880.4930371165024,
 -60376.87303604806,
 133845.51315972456,
 42215.29248023439,
 -85341.0412992822,
 247960.6986862305,
 -151988.30144799507,
 63927.621114863454,
 -31932.870620731654,
 -138347.6612687276,
 -24597.351135074416,
 119068.10438624921,
 42022.461999232684,
 -139278.21181216618,
 -60067.06266196328,
 7329.217462206869,
 -69239.60875780974,
 -86034.08434491743,
 210796.53486417234,
 -25420.864188908497,
 197915.8380609026,
 3065.7212228862218,
 52790.32224006233,
 -14928.524703838975,
 -51421.110532170744,
 33618.89824858968,
 -14639.895459143292,
 48170.57789377734,
 -273998.68721588457,
 44847.72443383352,
 178204.265280778,
 -75762.18360416162,
 81942.58075417246,
 24683.00263666674,
 -5808.794368686405,
 -2.2919266484677792e-10,
 -10547.532373326403,
 7011.683153712987,
 37709.41100917447,
 2454.0166765378503,
 -11658.059711216283,
 -18464.675018003174,
 68705.14370544029,
 -117630.4228576728,
 412.4036726808921,
 -80746.82401451944,
 43307.40198081364,
 -630.4736664755433,
 14699.128106545984,
 -9972.588683342081,
 100081.40347668338,
 36028.776863448664,
 27132.688301052793,
 -144886.74873711145,
 -64059.30856336346,
 -18916.62578976374,
 121707.78402008912,
 62118.42615247322,
 48028.36723223583,
 7373.540837787578,
 -264069.67430238036,
 -92165.84364855484,
 74982.72725621125,
 -21262.995777982233]

In [276]:
X_col = X.columns
X_col = list(X_col)
X_col

['Restaurants',
 'Supermarkets',
 'Liquor Store',
 'Schools',
 'Churches',
 'Convenience_Store',
 'Drugstore',
 'Fire_Station',
 'Hospital',
 'Bar',
 'House Type_x_CONDOMINIUM OFC  OR OTHER COM CONDO',
 'House Type_x_DUPLEX',
 'House Type_x_MOBILE HOME',
 'House Type_x_QUADPLEX',
 'House Type_x_RESIDENTIAL COMBO/MISC',
 'House Type_x_RESIDENTIAL CONDO',
 'House Type_x_RURAL COMBO',
 'House Type_x_SINGLE FAMILY',
 'House Type_x_SMALL SERVICE SHOP',
 'House Type_x_SPLIT CLASS',
 'House Type_x_TRIPLEX',
 'House Type_x_VACANT RESIDENTIAL LAND',
 'House Type_x_VACANT RURAL LAND',
 'House Type_x_ZERO LOT LINE',
 'Zone_x_1',
 'Zone_x_2',
 'Zone_x_3',
 'Zone_x_4',
 'Zone_x_5',
 'Zone_x_6',
 'Zone_x_7',
 'Zone_x_8',
 'Zone_x_9',
 'Property City_x_ANTIOCH',
 'Property City_x_BRENTWOOD',
 'Property City_x_GOODLETTSVILLE',
 'Property City_x_HERMITAGE',
 'Property City_x_JOELTON',
 'Property City_x_MADISON',
 'Property City_x_NASHVILLE',
 'Property City_x_NOLENSVILLE',
 'Property City_x_OLD HICKORY',
 'Property City_x_PEGRAM',
 'Property City_x_WHITES CREEK',
 'Add. End_100',
 'Add. End_70',
 'Add. End_ALY',
 'Add. End_AVE',
 'Add. End_BLVD',
 'Add. End_BROADWAY',
 'Add. End_CIR',
 'Add. End_CT',
 'Add. End_CV',
 'Add. End_DR',
 'Add. End_E',
 'Add. End_GRN',
 'Add. End_GRNS',
 'Add. End_GRV',
 'Add. End_LN',
 'Add. End_N',
 'Add. End_PASS',
 'Add. End_PIKE',
 'Add. End_PKWY',
 'Add. End_PL',
 'Add. End_PT',
 'Add. End_RD',
 'Add. End_REEF',
 'Add. End_RUN',
 'Add. End_S',
 'Add. End_ST',
 'Add. End_STA',
 'Add. End_TER',
 'Add. End_TRCE',
 'Add. End_TRL',
 'Add. End_VILLA',
 'Add. End_W',
 'Add. End_WAY',
 'Add. End_XING']

In [278]:
from sklearn.feature_selection import f_classif

fc = f_classif(X,y)
fc

C:\Users\CFP76\anaconda3\envs\PythonData\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:116: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw

(array([0.99675477, 1.16490672, 1.2491597 , 1.43800792, 0.97271962,
        1.22258969, 1.25165194, 1.26915218, 1.31471142, 1.40149952,
        0.5642564 , 1.22436438, 0.22515296,        inf, 0.1874748 ,
        1.2553695 , 1.35348255, 1.43028149, 0.5642564 , 1.12942879,
               inf, 2.13951834, 0.49470711, 1.57153499, 1.23358771,
        1.52626465, 1.04110021, 1.21988244, 1.64951045, 1.05180107,
        1.08020551, 1.32089117, 1.37583144, 1.42461015, 1.98481925,
        1.29509498, 0.9787694 , 3.15211413, 1.04994828, 1.31432241,
        2.80789987, 1.30710797, 0.90933768, 1.3142479 ,        inf,
               inf, 0.37464426, 1.10719968, 1.89173649, 0.10184262,
        1.41485718, 0.97657227, 1.98877832, 1.18564337,        inf,
               inf, 0.1403771 ,        inf, 1.05253167, 1.07953997,
        3.38279038, 1.18690476, 0.53610137, 0.79888937,        inf,
        1.3075249 , 0.07982291, 0.11979879, 0.59566429, 1.00656854,
               inf, 2.14902078, 2.44209273, 1.3749276 ,        inf,
        0.5628824 , 1.48513343, 0.1403771 ]),
 array([5.15403166e-01, 2.90395079e-02, 2.87429869e-03, 3.28315374e-06,
        6.33437707e-01, 6.29842922e-03, 2.66386044e-03, 1.54413448e-03,
        3.41477877e-04, 1.40228791e-05, 1.00000000e+00, 5.98597051e-03,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.37643473e-03,
        8.60747727e-05, 4.48599227e-06, 1.00000000e+00, 6.53652604e-02,
        0.00000000e+00, 3.07380627e-21, 1.00000000e+00, 1.03936058e-08,
        4.57882583e-03, 7.84834606e-08, 3.08207795e-01, 6.80387226e-03,
        2.77391445e-10, 2.65083930e-01, 1.68958785e-01, 2.75665051e-04,
        3.75168648e-05, 5.63191535e-06, 1.19113634e-17, 6.63999976e-04,
        6.04181861e-01, 5.99590649e-45, 2.72295850e-01, 3.46086090e-04,
        5.31898223e-37, 4.43060464e-04, 8.79925494e-01, 3.46975428e-04,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.03017545e-01,
        1.55734226e-15, 1.00000000e+00, 8.30084579e-06, 6.14864069e-01,
        9.66286725e-18, 1.72530994e-02, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.62270434e-01, 1.70893100e-01,
        3.81089612e-50, 1.66974116e-02, 1.00000000e+00, 9.97208237e-01,
        0.00000000e+00, 4.36816305e-04, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 4.67010266e-01, 0.00000000e+00, 1.84159175e-21,
        2.22680815e-28, 3.88171487e-05, 0.00000000e+00, 1.00000000e+00,
        4.63883953e-07, 1.00000000e+00]))

In [279]:
import statsmodels.api as sm

In [286]:
mod = sm.OLS(y,X)

res = mod.fit()

ressum = res.summary()

results_as_html = ressum.tables[1].as_html()
sumdf = pd.read_html(results_as_html, header=0, index_col=0)[0]

In [307]:
ressum

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:      Sale Price(USD)_y   R-squared:                       0.369
Model:                            OLS   Adj. R-squared:                  0.329
Method:                 Least Squares   F-statistic:                     9.186
Date:                Wed, 16 Feb 2022   Prob (F-statistic):           5.14e-74
Time:                        11:15:13   Log-Likelihood:                -16422.
No. Observations:                1235   AIC:                         3.299e+04
Df Residuals:                    1160   BIC:                         3.338e+04
Df Model:                          74
Covariance Type:            nonrobust
====================================================================================================================
                                                       coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------
Restaurants                                       6312.7175   4819.818      1.310      0.191   -3143.820    1.58e+04
Supermarkets                                     -4065.8902   1897.019     -2.143      0.032   -7787.863    -343.917
Liquor Store                                      8646.2214   1928.938      4.482      0.000    4861.623    1.24e+04
Schools                                          -8681.4381   4289.499     -2.024      0.043   -1.71e+04    -265.394
Churches                                          8911.9974   7063.169      1.262      0.207   -4946.020    2.28e+04
Convenience_Store                                -7174.5480   2582.152     -2.779      0.006   -1.22e+04   -2108.336
Drugstore                                          561.2120   2457.441      0.228      0.819   -4260.315    5382.739
Fire_Station                                      4930.1239   2973.973      1.658      0.098    -904.844    1.08e+04
Hospital                                          2618.7907   1423.911      1.839      0.066    -174.938    5412.520
Bar                                              -4578.8166   1994.869     -2.295      0.022   -8492.773    -664.861
House Type_x_CONDOMINIUM OFC  OR OTHER COM CONDO  1.334e+05   1.46e+05      0.917      0.359   -1.52e+05    4.19e+05
House Type_x_DUPLEX                               1.651e+05   3.83e+04      4.312      0.000       9e+04     2.4e+05
House Type_x_MOBILE HOME                         -7.808e+04   1.45e+05     -0.537      0.591   -3.63e+05    2.07e+05
House Type_x_QUADPLEX                              6.87e+04   1.06e+05      0.645      0.519    -1.4e+05    2.78e+05
House Type_x_RESIDENTIAL COMBO/MISC               9.242e+04   1.59e+05      0.580      0.562    -2.2e+05    4.05e+05
House Type_x_RESIDENTIAL CONDO                     3.95e+04   3.06e+04      1.292      0.197   -2.05e+04    9.95e+04
House Type_x_RURAL COMBO                          2.415e+04   1.07e+05      0.225      0.822   -1.86e+05    2.34e+05
House Type_x_SINGLE FAMILY                        1.201e+05   2.96e+04      4.057      0.000     6.2e+04    1.78e+05
House Type_x_SMALL SERVICE SHOP                   7160.9816   1.47e+05      0.049      0.961   -2.81e+05    2.95e+05
House Type_x_SPLIT CLASS                          3.691e+05   1.47e+05      2.509      0.012    8.04e+04    6.58e+05
House Type_x_TRIPLEX                              -7.68e+04   1.45e+05     -0.528      0.598   -3.62e+05    2.09e+05
House Type_x_VACANT RESIDENTIAL LAND              1.574e+05   3.58e+04      4.398      0.000    8.72e+04    2.28e+05
House Type_x_VACANT RURAL LAND                    2.659e+04   7.19e+04      0.370      0.712   -1.14e+05    1.68e+05
House Type_x_ZERO LOT LINE                        -5.43e+04   4.13e+04     -1.316      0.189   -1.35e+05    2.67e+04
Zone_x_1                                          8.335e+04   3.32e+04      2.513      0.012    1.83e+04    1.48e+05
Zone_x_2                                          2.332e+05   3.19e+04      7.308      0.000    1.71e+05    2.96e+05
Zone_x_3                                          1.517e+05    3.2e+04      4.746      0.000     8.9e+04    2.14e+05
Zone_x_4                                         -6874.5660   3.76e+04     -0.183      0.855   -8.07e+04     6.7e+04
Zone_x_5                                          4.839e+04    3.9e+04      1.239      0.215   -2.82e+04    1.25e+05
Zone_x_6                                          1.231e+05   3.46e+04      3.556      0.000    5.52e+04    1.91e+05
Zone_x_7                                          4.658e+04   3.78e+04      1.232      0.218   -2.76e+04    1.21e+05
Zone_x_8                                          3.481e+04   3.38e+04      1.030      0.303   -3.15e+04    1.01e+05
Zone_x_9                                          2.802e+05    4.2e+04      6.673      0.000    1.98e+05    3.63e+05
Property City_x_ANTIOCH                           4.907e+04   3.81e+04      1.287      0.198   -2.57e+04    1.24e+05
Property City_x_BRENTWOOD                         2.847e+05   4.31e+04      6.603      0.000       2e+05    3.69e+05
Property City_x_GOODLETTSVILLE                    9.384e+04   4.53e+04      2.070      0.039    4908.859    1.83e+05
Property City_x_HERMITAGE                         1.283e+05   3.97e+04      3.230      0.001    5.04e+04    2.06e+05
Property City_x_JOELTON                           1.231e+05   5.04e+04      2.443      0.015    2.43e+04    2.22e+05
Property City_x_MADISON                           2.625e+04   4.24e+04      0.620      0.536   -5.69e+04    1.09e+05
Property City_x_NASHVILLE                         1.032e+05   3.35e+04      3.079      0.002    3.74e+04    1.69e+05
Property City_x_NOLENSVILLE                       7.074e+04   5.46e+04      1.295      0.196   -3.65e+04    1.78e+05
Property City_x_OLD HICKORY                       1.447e+05   4.34e+04      3.333      0.001    5.95e+04     2.3e+05
Property City_x_PEGRAM                           -1.117e+05   9.25e+04     -1.208      0.227   -2.93e+05    6.97e+04
Property City_x_WHITES CREEK                      8.226e+04   7.96e+04      1.033      0.302    -7.4e+04    2.39e+05
Add. End_100                                      2.174e+05   1.47e+05      1.483      0.138   -7.02e+04    5.05e+05
Add. End_70                                       1.215e+04   1.55e+05      0.078      0.938   -2.93e+05    3.17e+05
Add. End_ALY                                       7.76e+04    1.1e+05      0.707      0.480   -1.38e+05    2.93e+05
Add. End_AVE                                      6.773e+04   2.25e+04      3.005      0.003    2.35e+04    1.12e+05
Add. End_BLVD                                     1.815e+04   2.89e+04      0.627      0.531   -3.86e+04    7.49e+04
Add. End_BROADWAY                                -1.248e+05   1.47e+05     -0.851      0.395   -4.12e+05    1.63e+05
Add. End_CIR                                      2.594e+04   2.76e+04      0.941      0.347   -2.81e+04       8e+04
Add. End_CT                                       3.773e+04   2.33e+04      1.618      0.106   -8023.885    8.35e+04
Add. End_CV                                       7.334e+04   6.81e+04      1.077      0.282   -6.02e+04    2.07e+05
Add. End_DR                                       4.121e+04   1.91e+04      2.157      0.031    3720.654    7.87e+04
Add. End_E                                        8.019e+04   1.05e+05      0.766      0.444   -1.25e+05    2.86e+05
Add. End_GRN                                      1.764e+04   1.49e+05      0.118      0.906   -2.76e+05    3.11e+05
Add. End_GRNS                                     8.896e+04   1.47e+05      0.605      0.546      -2e+05    3.78e+05
Add. End_GRV                                     -1.033e+05   1.07e+05     -0.965      0.335   -3.13e+05    1.07e+05
Add. End_LN                                       4.965e+04   2.38e+04      2.084      0.037    2907.911    9.64e+04
Add. End_N                                        -3.21e+04   3.17e+04     -1.012      0.312   -9.43e+04    3.01e+04
Add. End_PASS                                     7.714e+04   8.73e+04      0.884      0.377   -9.41e+04    2.48e+05
Add. End_PIKE                                     -970.9667   3.61e+04     -0.027      0.979   -7.17e+04    6.98e+04
Add. End_PKWY                                     1.239e+04   6.77e+04      0.183      0.855    -1.2e+05    1.45e+05
Add. End_PL                                       5623.0758   2.95e+04      0.190      0.849   -5.23e+04    6.36e+04
Add. End_PT                                       1.148e+05   1.04e+05      1.101      0.271   -8.98e+04    3.19e+05
Add. End_RD                                       6.178e+04   2.19e+04      2.820      0.005    1.88e+04    1.05e+05
Add. End_REEF                                      7.45e+04   1.48e+05      0.505      0.614   -2.15e+05    3.64e+05
Add. End_RUN                                     -1.355e+04   1.06e+05     -0.128      0.898   -2.21e+05    1.93e+05
Add. End_S                                         1.01e+04   3.95e+04      0.256      0.798   -6.74e+04    8.76e+04
Add. End_ST                                       6274.2083   2.46e+04      0.255      0.799    -4.2e+04    5.46e+04
Add. End_STA                                      1.559e+05   1.48e+05      1.053      0.292   -1.35e+05    4.46e+05
Add. End_TER                                      6.072e+04   7.53e+04      0.807      0.420    -8.7e+04    2.08e+05
Add. End_TRCE                                     3.436e+04   4.79e+04      0.718      0.473   -5.96e+04    1.28e+05
Add. End_TRL                                      5.206e+04   4.79e+04      1.088      0.277   -4.18e+04    1.46e+05
Add. End_VILLA                                   -2.387e+05    1.5e+05     -1.595      0.111   -5.32e+05     5.5e+04
Add. End_W                                       -5.631e+04   1.05e+05     -0.535      0.593   -2.63e+05     1.5e+05
Add. End_WAY                                      9.119e+04   3.04e+04      2.995      0.003    3.15e+04    1.51e+05
Add. End_XING                                     -354.8223   1.47e+05     -0.002      0.998   -2.88e+05    2.87e+05
==============================================================================
Omnibus:                       70.604   Durbin-Watson:                   1.815
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              106.750
Skew:                           0.471   Prob(JB):                     6.60e-24
Kurtosis:                       4.090   Cond. No.                     3.41e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.48e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [328]:
sumdf.index

Index(['Restaurants', 'Supermarkets', 'Liquor Store', 'Schools', 'Churches',
       'Convenience_Store', 'Drugstore', 'Fire_Station', 'Hospital', 'Bar',
       'House Type_x_CONDOMINIUM OFC OR OTHER COM CONDO',
       'House Type_x_DUPLEX', 'House Type_x_MOBILE HOME',
       'House Type_x_QUADPLEX', 'House Type_x_RESIDENTIAL COMBO/MISC',
       'House Type_x_RESIDENTIAL CONDO', 'House Type_x_RURAL COMBO',
       'House Type_x_SINGLE FAMILY', 'House Type_x_SMALL SERVICE SHOP',
       'House Type_x_SPLIT CLASS', 'House Type_x_TRIPLEX',
       'House Type_x_VACANT RESIDENTIAL LAND',
       'House Type_x_VACANT RURAL LAND', 'House Type_x_ZERO LOT LINE',
       'Zone_x_1', 'Zone_x_2', 'Zone_x_3', 'Zone_x_4', 'Zone_x_5', 'Zone_x_6',
       'Zone_x_7', 'Zone_x_8', 'Zone_x_9', 'Property City_x_ANTIOCH',
       'Property City_x_BRENTWOOD', 'Property City_x_GOODLETTSVILLE',
       'Property City_x_HERMITAGE', 'Property City_x_JOELTON',
       'Property City_x_MADISON', 'Property City_x_NASHVILLE',
       'Property City_x_NOLENSVILLE', 'Property City_x_OLD HICKORY',
       'Property City_x_PEGRAM', 'Property City_x_WHITES CREEK',
       'Add. End_100', 'Add. End_70', 'Add. End_ALY', 'Add. End_AVE',
       'Add. End_BLVD', 'Add. End_BROADWAY', 'Add. End_CIR', 'Add. End_CT',
       'Add. End_CV', 'Add. End_DR', 'Add. End_E', 'Add. End_GRN',
       'Add. End_GRNS', 'Add. End_GRV', 'Add. End_LN', 'Add. End_N',
       'Add. End_PASS', 'Add. End_PIKE', 'Add. End_PKWY', 'Add. End_PL',
       'Add. End_PT', 'Add. End_RD', 'Add. End_REEF', 'Add. End_RUN',
       'Add. End_S', 'Add. End_ST', 'Add. End_STA', 'Add. End_TER',
       'Add. End_TRCE', 'Add. End_TRL', 'Add. End_VILLA', 'Add. End_W',
       'Add. End_WAY', 'Add. End_XING'],
      dtype='object')

In [289]:
sumdf.sort_values(by='P>|t|')

,coef,std err,t,P>|t|,[0.025,0.975]
House Type_x_SINGLE FAMILY,120100.0000,29600.0,4.057,0.000,62000.0,178000.0
Property City_x_BRENTWOOD,284700.0000,43100.0,6.603,0.000,200000.0,369000.0
Zone_x_2,233200.0000,31900.0,7.308,0.000,171000.0,296000.0
Zone_x_3,151700.0000,32000.0,4.746,0.000,89000.0,214000.0
House Type_x_VACANT RESIDENTIAL LAND,157400.0000,35800.0,4.398,0.000,87200.0,228000.0
...,...,...,...,...,...,...
Add. End_GRN,17640.0000,149000.0,0.118,0.906,-276000.0,311000.0
Add. End_70,12150.0000,155000.0,0.078,0.938,-293000.0,317000.0
House Type_x_SMALL SERVICE SHOP,7160.9816,147000.0,0.049,0.961,-281000.0,295000.0
Add. End_PIKE,-970.9667,36100.0,-0.027,0.979,-71700.0,69800.0
Add. End_XING,-354.8223,147000.0,-0.002,0.998,-288000.0,287000.0

In [291]:
sumdf.dtypes

coef       float64
std err    float64
t          float64
P>|t|      float64
[0.025     float64
0.975]     float64
dtype: object

In [294]:
statsigdf = sumdf[sumdf['P>|t|'] <= 0.05]

In [298]:
statsigdf = statsigdf.sort_values(by='t')

In [324]:
statsigdf

,coef,std err,t,P>|t|,[0.025,0.975]
Convenience_Store,-7174.5480,2582.152,-2.779,0.006,-12200.000,-2108.336
Bar,-4578.8166,1994.869,-2.295,0.022,-8492.773,-664.861
Supermarkets,-4065.8902,1897.019,-2.143,0.032,-7787.863,-343.917
Schools,-8681.4381,4289.499,-2.024,0.043,-17100.000,-265.394
Property City_x_GOODLETTSVILLE,93840.0000,45300.000,2.070,0.039,4908.859,183000.000
Add. End_LN,49650.0000,23800.000,2.084,0.037,2907.911,96400.000
Add. End_DR,41210.0000,19100.000,2.157,0.031,3720.654,78700.000
Property City_x_JOELTON,123100.0000,50400.000,2.443,0.015,24300.000,222000.000
House Type_x_SPLIT CLASS,369100.0000,147000.000,2.509,0.012,80400.000,658000.000
Zone_x_1,83350.0000,33200.000,2.513,0.012,18300.000,148000.000
Add. End_RD,61780.0000,21900.000,2.820,0.005,18800.000,105000.000
Add. End_WAY,91190.0000,30400.000,2.995,0.003,31500.000,151000.000
Add. End_AVE,67730.0000,22500.000,3.005,0.003,23500.000,112000.000
Property City_x_NASHVILLE,103200.0000,33500.000,3.079,0.002,37400.000,169000.000
Property City_x_HERMITAGE,128300.0000,39700.000,3.230,0.001,50400.000,206000.000
Property City_x_OLD HICKORY,144700.0000,43400.000,3.333,0.001,59500.000,230000.000
Zone_x_6,123100.0000,34600.000,3.556,0.000,55200.000,191000.000
House Type_x_SINGLE FAMILY,120100.0000,29600.000,4.057,0.000,62000.000,178000.000
House Type_x_DUPLEX,165100.0000,38300.000,4.312,0.000,90000.000,240000.000
House Type_x_VACANT RESIDENTIAL LAND,157400.0000,35800.000,4.398,0.000,87200.000,228000.000
Liquor Store,8646.2214,1928.938,4.482,0.000,4861.623,12400.000
Zone_x_3,151700.0000,32000.000,4.746,0.000,89000.000,214000.000
Property City_x_BRENTWOOD,284700.0000,43100.000,6.603,0.000,200000.000,369000.000
Zone_x_9,280200.0000,42000.000,6.673,0.000,198000.000,363000.000
Zone_x_2,233200.0000,31900.000,7.308,0.000,171000.000,296000.000

In [314]:
modtrain = sm.OLS(y_train,X_train)

restrain = modtrain.fit()

restrainsum = restrain.summary()

resultstrain_as_html = restrainsum.tables[1].as_html()
trainsumdf = pd.read_html(resultstrain_as_html, header=0, index_col=0)[0]

In [315]:
restrainsum

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:      Sale Price(USD)_y   R-squared:                       0.393
Model:                            OLS   Adj. R-squared:                  0.341
Method:                 Least Squares   F-statistic:                     7.564
Date:                Wed, 16 Feb 2022   Prob (F-statistic):           2.72e-54
Time:                        14:09:30   Log-Likelihood:                -12309.
No. Observations:                 926   AIC:                         2.477e+04
Df Residuals:                     852   BIC:                         2.512e+04
Df Model:                          73
Covariance Type:            nonrobust
====================================================================================================================
                                                       coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------
Restaurants                                       5385.8701   5711.418      0.943      0.346   -5824.229    1.66e+04
Supermarkets                                     -5307.3646   2241.107     -2.368      0.018   -9706.102    -908.627
Liquor Store                                      8616.4756   2269.851      3.796      0.000    4161.321    1.31e+04
Schools                                          -1.138e+04   4900.860     -2.323      0.020    -2.1e+04   -1764.363
Churches                                          7931.9204   8941.381      0.887      0.375   -9617.795    2.55e+04
Convenience_Store                                -6445.3323   2943.711     -2.190      0.029   -1.22e+04    -667.558
Drugstore                                            7.5867   2841.839      0.003      0.998   -5570.239    5585.412
Fire_Station                                      6527.2734   3545.408      1.841      0.066    -431.483    1.35e+04
Hospital                                          1924.1419   1675.626      1.148      0.251   -1364.698    5212.981
Bar                                              -2967.0188   2396.260     -1.238      0.216   -7670.283    1736.246
House Type_x_CONDOMINIUM OFC  OR OTHER COM CONDO  1.475e+05   1.48e+05      0.997      0.319   -1.43e+05    4.38e+05
House Type_x_DUPLEX                                1.64e+05   4.46e+04      3.675      0.000    7.64e+04    2.52e+05
House Type_x_MOBILE HOME                         -5.963e+04   1.48e+05     -0.404      0.686   -3.49e+05     2.3e+05
House Type_x_QUADPLEX                             7.954e+04   1.09e+05      0.728      0.467   -1.35e+05    2.94e+05
House Type_x_RESIDENTIAL COMBO/MISC                9.02e+04   1.75e+05      0.514      0.607   -2.54e+05    4.34e+05
House Type_x_RESIDENTIAL CONDO                    2.794e+04   3.46e+04      0.807      0.420      -4e+04    9.59e+04
House Type_x_RURAL COMBO                          2.222e+05   1.53e+05      1.453      0.147    -7.8e+04    5.22e+05
House Type_x_SINGLE FAMILY                        1.305e+05   3.35e+04      3.895      0.000    6.48e+04    1.96e+05
House Type_x_SMALL SERVICE SHOP                   2974.0287   1.49e+05      0.020      0.984    -2.9e+05    2.96e+05
House Type_x_SPLIT CLASS                          3.363e+05    1.5e+05      2.241      0.025    4.18e+04    6.31e+05
House Type_x_TRIPLEX                             -6.367e+04   1.48e+05     -0.431      0.667   -3.54e+05    2.26e+05
House Type_x_VACANT RESIDENTIAL LAND              1.522e+05   3.95e+04      3.851      0.000    7.47e+04     2.3e+05
House Type_x_VACANT RURAL LAND                    5.638e+04   8.28e+04      0.681      0.496   -1.06e+05    2.19e+05
House Type_x_ZERO LOT LINE                       -5.003e+04   4.47e+04     -1.121      0.263   -1.38e+05    3.76e+04
Zone_x_1                                          1.128e+05   3.83e+04      2.942      0.003    3.75e+04    1.88e+05
Zone_x_2                                          2.564e+05   3.69e+04      6.952      0.000    1.84e+05    3.29e+05
Zone_x_3                                          1.794e+05   3.76e+04      4.767      0.000    1.06e+05    2.53e+05
Zone_x_4                                         -1899.2141   4.39e+04     -0.043      0.966   -8.81e+04    8.43e+04
Zone_x_5                                          7.731e+04    4.5e+04      1.717      0.086    -1.1e+04    1.66e+05
Zone_x_6                                          1.447e+05   4.05e+04      3.577      0.000    6.53e+04    2.24e+05
Zone_x_7                                          6.814e+04   4.46e+04      1.529      0.127   -1.93e+04    1.56e+05
Zone_x_8                                          5.134e+04   3.89e+04      1.320      0.187    -2.5e+04    1.28e+05
Zone_x_9                                          3.482e+05   4.86e+04      7.166      0.000    2.53e+05    4.44e+05
Property City_x_ANTIOCH                           8.698e+04   4.63e+04      1.877      0.061   -3983.646    1.78e+05
Property City_x_BRENTWOOD                         3.103e+05   5.02e+04      6.178      0.000    2.12e+05    4.09e+05
Property City_x_GOODLETTSVILLE                    1.155e+05   5.42e+04      2.129      0.034    9004.290    2.22e+05
Property City_x_HERMITAGE                         1.652e+05   4.61e+04      3.587      0.000    7.48e+04    2.56e+05
Property City_x_JOELTON                           9.747e+04    5.5e+04      1.773      0.077   -1.04e+04    2.05e+05
Property City_x_MADISON                           6.098e+04   5.11e+04      1.194      0.233   -3.93e+04    1.61e+05
Property City_x_NASHVILLE                          1.46e+05   4.07e+04      3.588      0.000    6.61e+04    2.26e+05
Property City_x_NOLENSVILLE                       9.776e+04   6.65e+04      1.471      0.142   -3.27e+04    2.28e+05
Property City_x_OLD HICKORY                       1.606e+05   5.07e+04      3.167      0.002     6.1e+04     2.6e+05
Property City_x_PEGRAM                           -1.616e+05   1.17e+05     -1.380      0.168   -3.91e+05    6.82e+04
Property City_x_WHITES CREEK                      1.572e+05    1.1e+05      1.429      0.153   -5.88e+04    3.73e+05
Add. End_100                                      2.157e+05   1.48e+05      1.457      0.145   -7.48e+04    5.06e+05
Add. End_70                                       -3.83e+04    1.6e+05     -0.239      0.811   -3.53e+05    2.76e+05
Add. End_ALY                                      1.194e+05   1.53e+05      0.778      0.437   -1.82e+05     4.2e+05
Add. End_AVE                                      6.215e+04   2.62e+04      2.376      0.018    1.08e+04    1.13e+05
Add. End_BLVD                                     3.166e+04   3.37e+04      0.941      0.347   -3.44e+04    9.77e+04
Add. End_BROADWAY                                -4.131e-13   8.29e-11     -0.005      0.996   -1.63e-10    1.62e-10
Add. End_CIR                                      2.692e+04   3.06e+04      0.880      0.379   -3.31e+04    8.69e+04
Add. End_CT                                       4.448e+04    2.7e+04      1.649      0.099   -8454.579    9.74e+04
Add. End_CV                                       7.518e+04   6.95e+04      1.082      0.279   -6.11e+04    2.11e+05
Add. End_DR                                       3.992e+04   2.19e+04      1.821      0.069   -3098.877    8.29e+04
Add. End_E                                        2.581e+04    1.5e+05      0.173      0.863   -2.68e+05    3.19e+05
Add. End_GRN                                        1.9e+04   1.51e+05      0.126      0.900   -2.78e+05    3.16e+05
Add. End_GRNS                                     1.062e+05   1.49e+05      0.714      0.476   -1.86e+05    3.98e+05
Add. End_GRV                                     -8.016e+04   1.08e+05     -0.740      0.459   -2.93e+05    1.32e+05
Add. End_LN                                       3.788e+04   2.77e+04      1.369      0.171   -1.64e+04    9.22e+04
Add. End_N                                       -4.328e+04   3.74e+04     -1.157      0.248   -1.17e+05    3.02e+04
Add. End_PASS                                     8.077e+04   8.91e+04      0.906      0.365   -9.41e+04    2.56e+05
Add. End_PIKE                                     3.684e+04   4.28e+04      0.860      0.390   -4.73e+04    1.21e+05
Add. End_PKWY                                     5.217e+04   7.68e+04      0.679      0.497   -9.86e+04    2.03e+05
Add. End_PL                                       2.749e+04   3.58e+04      0.768      0.443   -4.28e+04    9.78e+04
Add. End_PT                                       1.375e+05   1.48e+05      0.931      0.352   -1.52e+05    4.27e+05
Add. End_RD                                        7.35e+04   2.52e+04      2.922      0.004    2.41e+04    1.23e+05
Add. End_REEF                                      6.46e+04   1.49e+05      0.433      0.665   -2.28e+05    3.58e+05
Add. End_RUN                                     -1.074e+05    1.5e+05     -0.715      0.475   -4.02e+05    1.88e+05
Add. End_S                                       -2.659e+04   5.68e+04     -0.468      0.640   -1.38e+05     8.5e+04
Add. End_ST                                       1.855e+04   2.88e+04      0.644      0.519   -3.79e+04     7.5e+04
Add. End_STA                                      1.592e+05   1.49e+05      1.065      0.287   -1.34e+05    4.52e+05
Add. End_TER                                      9.959e+04   8.78e+04      1.134      0.257   -7.28e+04    2.72e+05
Add. End_TRCE                                      8.55e+04   5.99e+04      1.426      0.154   -3.22e+04    2.03e+05
Add. End_TRL                                      4.484e+04   5.64e+04      0.795      0.427   -6.58e+04    1.56e+05
Add. End_VILLA                                   -2.266e+05   1.53e+05     -1.485      0.138   -5.26e+05    7.28e+04
Add. End_W                                        -5.47e+04   1.07e+05     -0.512      0.608   -2.64e+05    1.55e+05
Add. End_WAY                                      1.124e+05   3.54e+04      3.180      0.002    4.31e+04    1.82e+05
Add. End_XING                                      1.62e+04   1.48e+05      0.110      0.913   -2.74e+05    3.06e+05
==============================================================================
Omnibus:                       54.652   Durbin-Watson:                   1.949
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               75.959
Skew:                           0.504   Prob(JB):                     3.20e-17
Kurtosis:                       3.976   Cond. No.                     1.11e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.74e-28. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [309]:
trainsumdf

                       coef     std err      t  P>|t|      [0.025      0.975]
Restaurants       6312.7175    4819.818  1.310  0.191   -3143.820   15800.000
Supermarkets     -4065.8902    1897.019 -2.143  0.032   -7787.863    -343.917
Liquor Store      8646.2214    1928.938  4.482  0.000    4861.623   12400.000
Schools          -8681.4381    4289.499 -2.024  0.043  -17100.000    -265.394
Churches          8911.9974    7063.169  1.262  0.207   -4946.020   22800.000
...                     ...         ...    ...    ...         ...         ...
Add. End_TRL     52060.0000   47900.000  1.088  0.277  -41800.000  146000.000
Add. End_VILLA -238700.0000  150000.000 -1.595  0.111 -532000.000   55000.000
Add. End_W      -56310.0000  105000.000 -0.535  0.593 -263000.000  150000.000
Add. End_WAY     91190.0000   30400.000  2.995  0.003   31500.000  151000.000
Add. End_XING     -354.8223  147000.000 -0.002  0.998 -288000.000  287000.000

[78 rows x 6 columns]

In [310]:
trstatsigdf = trainsumdf[trainsumdf['P>|t|'] <= 0.05]
trstatsigdf = trstatsigdf.sort_values(by='t')
trstatsigdf

,coef,std err,t,P>|t|,[0.025,0.975]
Convenience_Store,-7174.5480,2582.152,-2.779,0.006,-12200.000,-2108.336
Bar,-4578.8166,1994.869,-2.295,0.022,-8492.773,-664.861
Supermarkets,-4065.8902,1897.019,-2.143,0.032,-7787.863,-343.917
Schools,-8681.4381,4289.499,-2.024,0.043,-17100.000,-265.394
Property City_x_GOODLETTSVILLE,93840.0000,45300.000,2.070,0.039,4908.859,183000.000
Add. End_LN,49650.0000,23800.000,2.084,0.037,2907.911,96400.000
Add. End_DR,41210.0000,19100.000,2.157,0.031,3720.654,78700.000
Property City_x_JOELTON,123100.0000,50400.000,2.443,0.015,24300.000,222000.000
House Type_x_SPLIT CLASS,369100.0000,147000.000,2.509,0.012,80400.000,658000.000
Zone_x_1,83350.0000,33200.000,2.513,0.012,18300.000,148000.000
Add. End_RD,61780.0000,21900.000,2.820,0.005,18800.000,105000.000
Add. End_WAY,91190.0000,30400.000,2.995,0.003,31500.000,151000.000
Add. End_AVE,67730.0000,22500.000,3.005,0.003,23500.000,112000.000
Property City_x_NASHVILLE,103200.0000,33500.000,3.079,0.002,37400.000,169000.000
Property City_x_HERMITAGE,128300.0000,39700.000,3.230,0.001,50400.000,206000.000
Property City_x_OLD HICKORY,144700.0000,43400.000,3.333,0.001,59500.000,230000.000
Zone_x_6,123100.0000,34600.000,3.556,0.000,55200.000,191000.000
House Type_x_SINGLE FAMILY,120100.0000,29600.000,4.057,0.000,62000.000,178000.000
House Type_x_DUPLEX,165100.0000,38300.000,4.312,0.000,90000.000,240000.000
House Type_x_VACANT RESIDENTIAL LAND,157400.0000,35800.000,4.398,0.000,87200.000,228000.000
Liquor Store,8646.2214,1928.938,4.482,0.000,4861.623,12400.000
Zone_x_3,151700.0000,32000.000,4.746,0.000,89000.000,214000.000
Property City_x_BRENTWOOD,284700.0000,43100.000,6.603,0.000,200000.000,369000.000
Zone_x_9,280200.0000,42000.000,6.673,0.000,198000.000,363000.000
Zone_x_2,233200.0000,31900.000,7.308,0.000,171000.000,296000.000

In [321]:
trstatsigdf.count()

coef       25
std err    25
t          25
P>|t|      25
[0.025     25
0.975]     25
dtype: int64

In [316]:
modtest = sm.OLS(y_test,X_test)

restest = modtest.fit()

restestsum = restest.summary()

resultstest_as_html = restestsum.tables[1].as_html()
testsumdf = pd.read_html(resultstest_as_html, header=0, index_col=0)[0]

In [317]:
restestsum

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:      Sale Price(USD)_y   R-squared:                       0.426
Model:                            OLS   Adj. R-squared:                  0.303
Method:                 Least Squares   F-statistic:                     3.484
Date:                Wed, 16 Feb 2022   Prob (F-statistic):           1.36e-11
Time:                        14:10:03   Log-Likelihood:                -4080.0
No. Observations:                 309   AIC:                             8270.
Df Residuals:                     254   BIC:                             8475.
Df Model:                          54
Covariance Type:            nonrobust
====================================================================================================================
                                                       coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------
Restaurants                                       8723.2030   1.02e+04      0.857      0.392   -1.13e+04    2.88e+04
Supermarkets                                     -1765.8398   3701.072     -0.477      0.634   -9054.536    5522.856
Liquor Store                                      7898.1820   3968.616      1.990      0.048      82.599    1.57e+04
Schools                                           5955.6269   1.09e+04      0.544      0.587   -1.56e+04    2.75e+04
Churches                                          4219.4357   1.33e+04      0.318      0.751   -2.19e+04    3.03e+04
Convenience_Store                                -1.106e+04   6009.256     -1.841      0.067   -2.29e+04     772.087
Drugstore                                         -664.0928   5269.530     -0.126      0.900    -1.1e+04    9713.443
Fire_Station                                      6439.3675   5950.685      1.082      0.280   -5279.599    1.82e+04
Hospital                                          4784.6527   2878.342      1.662      0.098    -883.803    1.05e+04
Bar                                              -1.007e+04   3875.930     -2.599      0.010   -1.77e+04   -2441.624
House Type_x_CONDOMINIUM OFC  OR OTHER COM CONDO -1.092e-09   3.11e-09     -0.351      0.726   -7.22e-09    5.04e-09
House Type_x_DUPLEX                               1.717e+05   7.59e+04      2.262      0.025    2.23e+04    3.21e+05
House Type_x_MOBILE HOME                          -2.35e-10   6.52e-10     -0.361      0.719   -1.52e-09    1.05e-09
House Type_x_QUADPLEX                             1.175e-09   1.46e-09      0.807      0.421   -1.69e-09    4.04e-09
House Type_x_RESIDENTIAL COMBO/MISC              -7.087e-10    1.4e-09     -0.505      0.614   -3.47e-09    2.06e-09
House Type_x_RESIDENTIAL CONDO                    1.043e+05   6.63e+04      1.572      0.117   -2.63e+04    2.35e+05
House Type_x_RURAL COMBO                          -2.69e+05   1.68e+05     -1.604      0.110   -5.99e+05    6.13e+04
House Type_x_SINGLE FAMILY                        1.234e+05   6.27e+04      1.967      0.050    -123.269    2.47e+05
House Type_x_SMALL SERVICE SHOP                   3.726e-11   7.02e-10      0.053      0.958   -1.34e-09    1.42e-09
House Type_x_SPLIT CLASS                         -8.227e-11   3.83e-10     -0.215      0.830   -8.37e-10    6.72e-10
House Type_x_TRIPLEX                              1.759e-10   3.83e-10      0.460      0.646   -5.77e-10    9.29e-10
House Type_x_VACANT RESIDENTIAL LAND              2.051e+05   8.62e+04      2.379      0.018    3.53e+04    3.75e+05
House Type_x_VACANT RURAL LAND                    1.411e+04   1.61e+05      0.088      0.930   -3.03e+05    3.31e+05
House Type_x_ZERO LOT LINE                       -2.922e+04   1.23e+05     -0.237      0.813   -2.72e+05    2.13e+05
Zone_x_1                                          3.574e+04   5.83e+04      0.613      0.540   -7.91e+04    1.51e+05
Zone_x_2                                          1.642e+05   5.53e+04      2.967      0.003    5.52e+04    2.73e+05
Zone_x_3                                          8.612e+04   5.35e+04      1.609      0.109   -1.93e+04    1.91e+05
Zone_x_4                                         -5.656e+04   6.71e+04     -0.843      0.400   -1.89e+05    7.56e+04
Zone_x_5                                         -1.621e+04   7.37e+04     -0.220      0.826   -1.61e+05    1.29e+05
Zone_x_6                                          7.266e+04   5.91e+04      1.229      0.220   -4.38e+04    1.89e+05
Zone_x_7                                         -2.893e+04   6.64e+04     -0.436      0.664    -1.6e+05    1.02e+05
Zone_x_8                                         -1.667e+04   6.04e+04     -0.276      0.783   -1.36e+05    1.02e+05
Zone_x_9                                          8.006e+04   7.88e+04      1.016      0.311   -7.51e+04    2.35e+05
Property City_x_ANTIOCH                          -2286.4598    6.5e+04     -0.035      0.972    -1.3e+05    1.26e+05
Property City_x_BRENTWOOD                         3.567e+05   1.02e+05      3.490      0.001    1.55e+05    5.58e+05
Property City_x_GOODLETTSVILLE                   -9645.3923   8.48e+04     -0.114      0.909   -1.77e+05    1.57e+05
Property City_x_HERMITAGE                          6.38e+04   8.01e+04      0.797      0.426   -9.39e+04    2.22e+05
Property City_x_JOELTON                           2.311e-10   1.07e-10      2.164      0.031    2.08e-11    4.41e-10
Property City_x_MADISON                          -6.359e+04   7.64e+04     -0.832      0.406   -2.14e+05    8.69e+04
Property City_x_NASHVILLE                         2.933e+04   5.71e+04      0.514      0.608   -8.31e+04    1.42e+05
Property City_x_NOLENSVILLE                      -8.156e+04   9.98e+04     -0.817      0.415   -2.78e+05    1.15e+05
Property City_x_OLD HICKORY                       1.241e+05   8.56e+04      1.450      0.148   -4.44e+04    2.93e+05
Property City_x_PEGRAM                           -1.043e+05   1.64e+05     -0.634      0.527   -4.28e+05     2.2e+05
Property City_x_WHITES CREEK                      7751.0355   1.22e+05      0.064      0.949   -2.32e+05    2.48e+05
Add. End_100                                      1.012e-10   5.48e-11      1.847      0.066    -6.7e-12    2.09e-10
Add. End_70                                       7.963e-11   6.99e-11      1.140      0.255    -5.8e-11    2.17e-10
Add. End_ALY                                      3.359e+04   1.54e+05      0.218      0.828    -2.7e+05    3.37e+05
Add. End_AVE                                      9.168e+04    3.8e+04      2.413      0.017    1.68e+04    1.67e+05
Add. End_BLVD                                    -3.315e+04   5.29e+04     -0.627      0.531   -1.37e+05     7.1e+04
Add. End_BROADWAY                                -1.523e+05   1.44e+05     -1.058      0.291   -4.36e+05    1.31e+05
Add. End_CIR                                      8.963e+04   6.51e+04      1.377      0.170   -3.85e+04    2.18e+05
Add. End_CT                                       2.344e+04   4.29e+04      0.546      0.586   -6.11e+04    1.08e+05
Add. End_CV                                       1.408e-11   2.85e-11      0.493      0.622   -4.21e-11    7.03e-11
Add. End_DR                                       5.271e+04   3.19e+04      1.654      0.099   -1.01e+04    1.15e+05
Add. End_E                                        1.258e+05   1.46e+05      0.864      0.389   -1.61e+05    4.13e+05
Add. End_GRN                                              0          0        nan        nan           0           0
Add. End_GRNS                                             0          0        nan        nan           0           0
Add. End_GRV                                              0          0        nan        nan           0           0
Add. End_LN                                       9.907e+04   4.11e+04      2.413      0.017    1.82e+04     1.8e+05
Add. End_N                                       -7930.8048   5.54e+04     -0.143      0.886   -1.17e+05    1.01e+05
Add. End_PASS                                             0          0        nan        nan           0           0
Add. End_PIKE                                    -1.309e+05   6.61e+04     -1.979      0.049   -2.61e+05    -630.291
Add. End_PKWY                                     -1.03e+05   1.45e+05     -0.709      0.479   -3.89e+05    1.83e+05
Add. End_PL                                      -5.508e+04    4.7e+04     -1.171      0.243   -1.48e+05    3.76e+04
Add. End_PT                                       1.302e+05   1.46e+05      0.894      0.372   -1.57e+05    4.17e+05
Add. End_RD                                       3.831e+04   3.89e+04      0.984      0.326   -3.84e+04    1.15e+05
Add. End_REEF                                             0          0        nan        nan           0           0
Add. End_RUN                                      9.902e+04   1.64e+05      0.604      0.546   -2.24e+05    4.22e+05
Add. End_S                                        2.705e+04   5.36e+04      0.504      0.614   -7.86e+04    1.33e+05
Add. End_ST                                      -1.625e+04   4.09e+04     -0.398      0.691   -9.67e+04    6.42e+04
Add. End_STA                                              0          0        nan        nan           0           0
Add. End_TER                                     -5.035e+04   1.45e+05     -0.347      0.729   -3.36e+05    2.35e+05
Add. End_TRCE                                    -3.382e+04   7.76e+04     -0.436      0.663   -1.87e+05    1.19e+05
Add. End_TRL                                      6.018e+04   9.26e+04      0.650      0.516   -1.22e+05    2.42e+05
Add. End_VILLA                                            0          0        nan        nan           0           0
Add. End_W                                                0          0        nan        nan           0           0
Add. End_WAY                                      3.243e+04   5.62e+04      0.577      0.565   -7.83e+04    1.43e+05
Add. End_XING                                             0          0        nan        nan           0           0
==============================================================================
Omnibus:                       14.502   Durbin-Watson:                   1.900
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               22.710
Skew:                           0.314   Prob(JB):                     1.17e-05
Kurtosis:                       4.170   Cond. No.                     1.11e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.93e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [318]:
testsumdf

                      coef    std err      t  P>|t|      [0.025      0.975]
Restaurants      8723.2030  10200.000  0.857  0.392  -11300.000   28800.000
Supermarkets    -1765.8398   3701.072 -0.477  0.634   -9054.536    5522.856
Liquor Store     7898.1820   3968.616  1.990  0.048      82.599   15700.000
Schools          5955.6269  10900.000  0.544  0.587  -15600.000   27500.000
Churches         4219.4357  13300.000  0.318  0.751  -21900.000   30300.000
...                    ...        ...    ...    ...         ...         ...
Add. End_TRL    60180.0000  92600.000  0.650  0.516 -122000.000  242000.000
Add. End_VILLA      0.0000      0.000    NaN    NaN       0.000       0.000
Add. End_W          0.0000      0.000    NaN    NaN       0.000       0.000
Add. End_WAY    32430.0000  56200.000  0.577  0.565  -78300.000  143000.000
Add. End_XING       0.0000      0.000    NaN    NaN       0.000       0.000

[78 rows x 6 columns]

In [319]:
testatsigdf = testsumdf[trainsumdf['P>|t|'] <= 0.05]
testatsigdf = trstatsigdf.sort_values(by='t')
testatsigdf

,coef,std err,t,P>|t|,[0.025,0.975]
Convenience_Store,-7174.5480,2582.152,-2.779,0.006,-12200.000,-2108.336
Bar,-4578.8166,1994.869,-2.295,0.022,-8492.773,-664.861
Supermarkets,-4065.8902,1897.019,-2.143,0.032,-7787.863,-343.917
Schools,-8681.4381,4289.499,-2.024,0.043,-17100.000,-265.394
Property City_x_GOODLETTSVILLE,93840.0000,45300.000,2.070,0.039,4908.859,183000.000
Add. End_LN,49650.0000,23800.000,2.084,0.037,2907.911,96400.000
Add. End_DR,41210.0000,19100.000,2.157,0.031,3720.654,78700.000
Property City_x_JOELTON,123100.0000,50400.000,2.443,0.015,24300.000,222000.000
House Type_x_SPLIT CLASS,369100.0000,147000.000,2.509,0.012,80400.000,658000.000
Zone_x_1,83350.0000,33200.000,2.513,0.012,18300.000,148000.000
Add. End_RD,61780.0000,21900.000,2.820,0.005,18800.000,105000.000
Add. End_WAY,91190.0000,30400.000,2.995,0.003,31500.000,151000.000
Add. End_AVE,67730.0000,22500.000,3.005,0.003,23500.000,112000.000
Property City_x_NASHVILLE,103200.0000,33500.000,3.079,0.002,37400.000,169000.000
Property City_x_HERMITAGE,128300.0000,39700.000,3.230,0.001,50400.000,206000.000
Property City_x_OLD HICKORY,144700.0000,43400.000,3.333,0.001,59500.000,230000.000
Zone_x_6,123100.0000,34600.000,3.556,0.000,55200.000,191000.000
House Type_x_SINGLE FAMILY,120100.0000,29600.000,4.057,0.000,62000.000,178000.000
House Type_x_DUPLEX,165100.0000,38300.000,4.312,0.000,90000.000,240000.000
House Type_x_VACANT RESIDENTIAL LAND,157400.0000,35800.000,4.398,0.000,87200.000,228000.000
Liquor Store,8646.2214,1928.938,4.482,0.000,4861.623,12400.000
Zone_x_3,151700.0000,32000.000,4.746,0.000,89000.000,214000.000
Property City_x_BRENTWOOD,284700.0000,43100.000,6.603,0.000,200000.000,369000.000
Zone_x_9,280200.0000,42000.000,6.673,0.000,198000.000,363000.000
Zone_x_2,233200.0000,31900.000,7.308,0.000,171000.000,296000.000

In [323]:
testatsigdf.count()

coef       25
std err    25
t          25
P>|t|      25
[0.025     25
0.975]     25
dtype: int64