In [72]:
# Dependencies and Setup
import pandas as pd
import numpy as np

In [73]:
df = pd.read_csv("housedata.csv")
df.head()

,PID,Property Address,Property City,House Type,Sale Price(USD),Sale Date,Latitude,Longitude,Zone,Unnamed: 9,Unnamed: 10
0,1,1100 CHEYENNE CIR,MADISON,SINGLE FAMILY,304000,9/7/2021,36.252414,-86.670697,6,NaN,NaN
1,2,3450 GREER RD,GOODLETTSVILLE,SINGLE FAMILY,405000,9/17/2021,36.383536,-86.783246,5,NaN,NaN
2,3,8565 WHITES CREEK PIKE,JOELTON,SINGLE FAMILY,666500,9/22/2021,36.381169,-86.894571,5,NaN,NaN
3,4,8560 COOPERTOWN RD,JOELTON,SINGLE FAMILY,620000,9/20/2021,36.380810,-86.906122,5,NaN,NaN
4,5,8409 RILEY ADCOCK RD,JOELTON,SINGLE FAMILY,227500,9/17/2021,36.372914,-86.883644,5,NaN,NaN

In [74]:
df.count()

PID                 1463
Property Address    1463
Property City       1463
House Type          1463
Sale Price(USD)     1463
Sale Date           1463
Latitude            1462
Longitude           1463
Zone                1463
Unnamed: 9             0
Unnamed: 10            0
dtype: int64

In [75]:
df.head()

,PID,Property Address,Property City,House Type,Sale Price(USD),Sale Date,Latitude,Longitude,Zone,Unnamed: 9,Unnamed: 10
0,1,1100 CHEYENNE CIR,MADISON,SINGLE FAMILY,304000,9/7/2021,36.252414,-86.670697,6,NaN,NaN
1,2,3450 GREER RD,GOODLETTSVILLE,SINGLE FAMILY,405000,9/17/2021,36.383536,-86.783246,5,NaN,NaN
2,3,8565 WHITES CREEK PIKE,JOELTON,SINGLE FAMILY,666500,9/22/2021,36.381169,-86.894571,5,NaN,NaN
3,4,8560 COOPERTOWN RD,JOELTON,SINGLE FAMILY,620000,9/20/2021,36.380810,-86.906122,5,NaN,NaN
4,5,8409 RILEY ADCOCK RD,JOELTON,SINGLE FAMILY,227500,9/17/2021,36.372914,-86.883644,5,NaN,NaN

In [76]:
df.loc[(df['House Type'] == 'RESIDENTIAL CONDO') & (df['Sale Price(USD)'] == 34131000)]

,PID,Property Address,Property City,House Type,Sale Price(USD),Sale Date,Latitude,Longitude,Zone,Unnamed: 9,Unnamed: 10
562,563,1204 49TH AVE N,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.162113,-86.845582,3,NaN,NaN
563,564,1216 49TH AVE N,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.162110,-86.845768,3,NaN,NaN
564,565,1212 49TH AVE N,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.162109,-86.845768,3,NaN,NaN
565,566,1206 49TH AVE N,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.162107,-86.845768,3,NaN,NaN
566,567,220 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161851,-86.844940,3,NaN,NaN
567,568,216 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161844,-86.844770,3,NaN,NaN
568,569,218 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161839,-86.844863,3,NaN,NaN
569,570,242 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161832,-86.845554,3,NaN,NaN
570,571,240 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161823,-86.845359,3,NaN,NaN
571,572,222 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161823,-86.845195,3,NaN,NaN
572,573,244 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161775,-86.845636,3,NaN,NaN
573,574,246 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161773,-86.845726,3,NaN,NaN
574,575,252 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161755,-86.845905,3,NaN,NaN
575,576,248 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161754,-86.845814,3,NaN,NaN
576,577,250 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161752,-86.845901,3,NaN,NaN
577,578,1210 49TH AVE N,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161744,-86.846379,3,NaN,NaN
578,579,212 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161734,-86.844643,3,NaN,NaN
579,580,224 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161679,-86.845310,3,NaN,NaN
580,581,236 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161677,-86.845325,3,NaN,NaN
581,582,238 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161675,-86.845349,3,NaN,NaN
582,583,1200 49TH AVE N,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161667,-86.845563,3,NaN,NaN
583,584,226 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161665,-86.845310,3,NaN,NaN
584,585,1214 49TH AVE N,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161664,-86.846071,3,NaN,NaN
585,586,210 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161659,-86.844614,3,NaN,NaN
586,587,234 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161594,-86.845319,3,NaN,NaN
587,588,228 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161587,-86.845310,3,NaN,NaN
588,589,232 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161586,-86.845323,3,NaN,NaN
589,590,208 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161582,-86.844601,3,NaN,NaN
590,591,258 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161519,-86.845797,3,NaN,NaN
591,592,206 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161506,-86.844612,3,NaN,NaN
593,594,262 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161498,-86.845647,3,NaN,NaN
594,595,264 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161492,-86.845600,3,NaN,NaN
595,596,260 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161488,-86.845793,3,NaN,NaN
596,597,256 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161487,-86.845986,3,NaN,NaN
597,598,230 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161476,-86.845378,3,NaN,NaN
598,599,204 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161438,-86.844613,3,NaN,NaN
599,600,200 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161360,-86.844592,3,NaN,NaN
600,601,261 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161344,-86.845644,3,NaN,NaN
601,602,259 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161340,-86.845789,3,NaN,NaN
602,603,257 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161336,-86.845844,3,NaN,NaN
604,605,1202 49TH AVE N,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161327,-86.846355,3,NaN,NaN
605,606,203 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161318,-86.844918,3,NaN,NaN
606,607,201 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161308,-86.844816,3,NaN,NaN
607,608,253 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161290,-86.846110,3,NaN,NaN
608,609,263 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161289,-86.845527,3,NaN,NaN
609,610,267 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161276,-86.845301,3,NaN,NaN
610,611,265 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161276,-86.845418,3,NaN,NaN
611,612,269 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161275,-86.845210,3,NaN,NaN
612,613,255 FOUNDERS LN,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161271,-86.846008,3,NaN,NaN
614,615,4714 TENNESSEE AVE,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161022,-86.844600,3,NaN,NaN
615,616,4718 TENNESSEE AVE,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161018,-86.844755,3,NaN,NaN
616,617,4720 TENNESSEE AVE,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161012,-86.844877,3,NaN,NaN
617,618,4716 TENNESSEE AVE,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161012,-86.844714,3,NaN,NaN
618,619,4724 TENNESSEE AVE,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161012,-86.845037,3,NaN,NaN
619,620,4722 TENNESSEE AVE,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.161010,-86.844950,3,NaN,NaN

In [79]:
df_clean = df.drop(df[(df['PID'] > 563) & (df['PID'] < 621)].index, axis = 0)

In [80]:
df_clean.loc[(df['House Type'] == 'RESIDENTIAL CONDO') & (df['Sale Price(USD)'] == 34131000)]

,PID,Property Address,Property City,House Type,Sale Price(USD),Sale Date,Latitude,Longitude,Zone,Unnamed: 9,Unnamed: 10
562,563,1204 49TH AVE N,NASHVILLE,RESIDENTIAL CONDO,34131000,9/16/2021,36.162113,-86.845582,3,NaN,NaN

In [85]:
df_clean = df.drop(['Unnamed: 9','Unnamed: 10'], axis=1)
df_clean.head()

,PID,Property Address,Property City,House Type,Sale Price(USD),Sale Date,Latitude,Longitude,Zone
0,1,1100 CHEYENNE CIR,MADISON,SINGLE FAMILY,304000,9/7/2021,36.252414,-86.670697,6
1,2,3450 GREER RD,GOODLETTSVILLE,SINGLE FAMILY,405000,9/17/2021,36.383536,-86.783246,5
2,3,8565 WHITES CREEK PIKE,JOELTON,SINGLE FAMILY,666500,9/22/2021,36.381169,-86.894571,5
3,4,8560 COOPERTOWN RD,JOELTON,SINGLE FAMILY,620000,9/20/2021,36.380810,-86.906122,5
4,5,8409 RILEY ADCOCK RD,JOELTON,SINGLE FAMILY,227500,9/17/2021,36.372914,-86.883644,5

In [110]:
df_clean = df_clean.dropna()

In [111]:
df_clean

,PID,Property Address,Property City,House Type,Sale Price(USD),Sale Date,Latitude,Longitude,Zone
0,1,1100 CHEYENNE CIR,MADISON,SINGLE FAMILY,304000,9/7/2021,36.252414,-86.670697,6
1,2,3450 GREER RD,GOODLETTSVILLE,SINGLE FAMILY,405000,9/17/2021,36.383536,-86.783246,5
2,3,8565 WHITES CREEK PIKE,JOELTON,SINGLE FAMILY,666500,9/22/2021,36.381169,-86.894571,5
3,4,8560 COOPERTOWN RD,JOELTON,SINGLE FAMILY,620000,9/20/2021,36.380810,-86.906122,5
4,5,8409 RILEY ADCOCK RD,JOELTON,SINGLE FAMILY,227500,9/17/2021,36.372914,-86.883644,5
...,...,...,...,...,...,...,...,...,...
1458,1459,4232 DYSANT ALY,NOLENSVILLE,SINGLE FAMILY,460000,9/13/2021,35.985114,-86.662269,1
1459,1460,1983 CAROTHERS RD,NOLENSVILLE,SINGLE FAMILY,497300,9/27/2021,35.984074,-86.622866,1
1460,1461,307 MOIRA CIR,NOLENSVILLE,RESIDENTIAL CONDO,300400,9/28/2021,35.983315,-86.622208,1
1461,1462,4154 ALVA LN,NOLENSVILLE,SINGLE FAMILY,500000,9/3/2021,35.983120,-86.663883,1
1462,1463,2027 OAK TRAIL DR,NOLENSVILLE,RESIDENTIAL CONDO,378900,9/13/2021,35.982863,-86.617761,1

In [116]:
df_clean = df_clean.drop(df[(df['PID'] > 139) & (df['PID'] < 145)].index, axis = 0)

KeyError: '[139 140 141 142 143] not found in axis'

In [115]:
df_clean = df_clean.drop(df[(df['PID'] == 157) & (df['PID'] == 158)].index, axis = 0)

In [118]:
df_clean = df_clean.drop(df[(df['PID'] > 139) & (df['PID'] < 145)].index, axis = 0)

KeyError: '[139 140 141 142 143] not found in axis'

In [119]:
df_clean = df_clean.drop(df[(df['PID'] == 72)].index, axis = 0)

In [120]:
df_clean = df_clean.drop(df[(df['PID'] == 192)].index, axis = 0)

In [122]:
df_clean = df_clean.drop(df[(df['PID'] == 199)].index, axis = 0)

KeyError: '[198] not found in axis'

In [123]:
df_clean = df_clean.drop(df[(df['PID'] == 245)].index, axis = 0)

In [124]:
df_clean = df_clean.drop(df[(df['PID'] == 286)].index, axis = 0)

In [125]:
df_clean = df_clean.drop(df[(df['PID'] == 310) & (df['PID'] == 311)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 400)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 415)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 428)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 464) & (df['PID'] == 472)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 499) & (df['PID'] == 500)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] > 517) & (df['PID'] < 526)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] > 563) & (df['PID'] < 593)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] > 593) & (df['PID'] < 604)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] > 604) & (df['PID'] < 614)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] > 614) & (df['PID'] < 621)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] > 626) & (df['PID'] < 650)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] > 663) & (df['PID'] < 668)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 669)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 696)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] > 707) & (df['PID'] < 711)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] > 717) & (df['PID'] < 720)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] > 743) & (df['PID'] < 747)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 761)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 765) & (df['PID'] == 766)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 780)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 785)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 803)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 807) & (df['PID'] == 808)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 829) & (df['PID'] == 831)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] > 857) & (df['PID'] < 861)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 894)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 903)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 964)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] > 967) & (df['PID'] < 971)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 989)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 1008)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 1029)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 1057)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 1060)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 1075)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 1100)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 1111)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 1135)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 1200)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 1204)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 1273)].index, axis = 0)
df_clean = df_clean.drop(df[(df['PID'] == 1328)].index, axis = 0)

KeyError: '[399] not found in axis'

In [127]:
df_clean.count()

PID                 1324
Property Address    1324
Property City       1324
House Type          1324
Sale Price(USD)     1324
Sale Date           1324
Latitude            1324
Longitude           1324
Zone                1324
dtype: int64

In [128]:
#Exporting the File to CSV
df_clean.to_csv('housedata_cleaned.csv')